name: ci

on:
  push:

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker tags
        id: docker_tag
        run: |
          tags="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            tags="$tags,ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest"
          fi
          echo "tags=$tags" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.docker_tag.outputs.tags }}